//mod print;
//mod var;
//mod types;
//mod string;
//mod tup;
//mod array;
//mod if_else;
//mod loops;
//mod func;
// mod pointers;
// mod structs;
// mod struct_fun;
// mod enums;
// mod cli;
//mod rps;
mod struct_ex;
mod prob1;
fn main() {
    //print::run();
    //var::run();
    //types::print();
    //string::run();
    //tup::start();
    //array::print();
    //array::vector();
    //if_else::run();
    //loops::for_loop();
    //func::run();
    // pointers::run();
    // structs::run();
    // struct_fun::run();
    // enums::print();
    //cli::run();
    //rps::run();
    struct_ex::run();
    prob1::solution1();
}
